import bcrypt from 'bcryptjs';

const data ={

    users:[
        {
            name: 'Chibuzor',
            email: 'admin@example.com',
            password: bcrypt.hashSync('123456'),
            isAdmin: true,
        },
    ],
    products: [
        {
            //_id: '1',
            name: 'Squat rack',
            slug: 'Squat-rack',
            categories: 'weightlighting',
            image: '/images/1.jpg',
            price: 230000,
            countInStock: 5,
            rating: 5,
            numReviews: 10,
            description: 'high quality squat rack',
        },
        {
            //_id: '2',
            name: 'Bench plus Squat rack',
            slug: 'Bench-plus-Squat-rack',
            categories: 'weightlighting',
            image: '/images/multi.jpg',
            price: 315000,
            countInStock: 5,
            rating: 5,
            numReviews: 10,
            description: 'high quality squat rack plus bench',
        },
        {
            //_id: '3',
            name: 'Weightlifting Bench',
            slug: 'weightlifting-bench',
            categories: 'weightlighting',
            image: '/images/2.jpg',
            price: 150000,
            countInStock: 5,
            rating: 5,
            numReviews: 10,
            description: 'high quality weightlifting bench',
        },
        {
            //_id: '4',
            name: 'Situp bench',
            slug: 'Situp-bench',
            categories: 'Body weight',
            image: '/images/situp.jpg',
            price: 30000,
            countInStock: 5,
            rating: 5,
            numReviews: 10,
            description: 'high quality situp bench',
        },
        {
            //_id: '5',
            name: 'Dumb Bell',
            slug: 'Dumb-Bell',
            categories: 'weight lifting',
            image: '/images/situp.jpg',
            price: 50000,
            countInStock: 5,
            rating: 5,
            numReviews: 10,
            description: 'high quality 20kg dumbell set',
        },
        {
            //_id: '6',
            name: 'Leg Press Machine',
            slug: ' Leg-Press-Machine',
            categories: 'weight lifting',
            image: '/images/leg.jpg',
            price: 500000,
            countInStock: 5,
            rating: 5,
            numReviews: 10,
            description: 'leg press machine',
        },
        {
            //_id: '7',
            name: 'Gym Station',
            slug: 'Gym-Station',
            categories: 'weight lifting',
            image: '/images/station.jpg',
            price: 1500000,
            countInStock: 5,
            rating: 5,
            numReviews: 10,
            description: 'Gym Station',
        },
        {
            //_id: '8',
            name: 'ThreadMill',
            slug: 'ThreadMill',
            categories: 'cardio',
            image: '/images/thread.jpg',
            price: 3000000,
            countInStock: 5,
            rating: 5,
            numReviews: 10,
            description: 'Gym Station',
        },
    ],
};

export default data;